---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: APPNAME
  name: APPNAME
spec:
  ports:
   - port: 80
     protocol: TCP
     targetPort: 80
  selector:
    app: APPNAME
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: APPNAME
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - partner.otomax.co.uk # update IP address here
      secretName: partner-otomax-cert-tls
  rules:
  - host: partner.otomax.co.uk 
    http:
      paths:
      - backend:
          serviceName: APPNAME
          servicePort: 80
        path: /
